"""Platform adapter and configuration generator for AevoraSEO multi-agent compatibility."""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from .models import AdapterResult, PlatformId, PlatformTier
from .registry import get_platform


def _aider_config(aevoraseo_root: str) -> str:
    return f"""# AevoraSEO Aider Configuration
# Auto-generated by aevoraseo agent adapt

read:
  - "{aevoraseo_root}/SKILL.md"

# Model and environment conventions
conventions:
  - ".aider.conventions.md"
"""


def _aider_conventions(aevoraseo_root: str) -> str:
    return f"""# AevoraSEO Conventions for Aider

When working on SEO, AEO, GEO, and website optimization:
1. Always follow the evidence-first rules in `{aevoraseo_root}/SKILL.md`.
2. Do not invent search rankings, volume, or citations without empirical data.
3. Run the native engine using `python {aevoraseo_root}/scripts/run.py <command>`.
4. Check engine readiness with `python {aevoraseo_root}/scripts/run.py doctor`.
"""


def _copilot_instructions(aevoraseo_root: str) -> str:
    return f"""# GitHub Copilot Instructions for AevoraSEO

This repository integrates with AevoraSEO for evidence-first SEO, AEO, and GEO intelligence.

## Operating Rules
- Follow instructions in `{aevoraseo_root}/SKILL.md`.
- Never manufacture search volumes, rankings, or fake AI citations.
- To execute SEO audits, use:
  ```bash
  python {aevoraseo_root}/scripts/run.py audit <url>
  node {aevoraseo_root}/bin/aevoraseo.js doctor
  ```
- All evidence records and diff snapshots are stored in SQLite or structured JSON/CSV.
"""


def _gemini_instructions(aevoraseo_root: str) -> str:
    return f"""# Gemini CLI Instructions for AevoraSEO

AevoraSEO is available for automated SEO, AEO, and GEO analysis.

## Usage
- Run diagnostics: `python {aevoraseo_root}/scripts/run.py doctor`
- Audit target: `python {aevoraseo_root}/scripts/run.py audit <url>`
- Content optimization: `python {aevoraseo_root}/scripts/run.py optimize <url>`
- Evidence rules: Consult `{aevoraseo_root}/SKILL.md` before recommending SEO changes.
"""


def generate_adapter(
    platform_id: PlatformId,
    workspace: Optional[str] = None,
    dry_run: bool = False,
    aevoraseo_root: Optional[str] = None,
) -> AdapterResult:
    """Generate configuration or instruction files for the target platform in the workspace."""
    spec = get_platform(platform_id)
    ws_path = Path(workspace).expanduser().resolve() if workspace else Path.cwd().resolve()

    if aevoraseo_root is None:
        aevoraseo_root = str(Path(__file__).resolve().parents[3])

    files_written: List[str] = []
    instructions: List[str] = []

    if platform_id == PlatformId.AIDER:
        conf_path = ws_path / ".aider.conf.yml"
        conv_path = ws_path / ".aider.conventions.md"

        if not dry_run:
            if not conf_path.exists():
                conf_path.write_text(_aider_config(aevoraseo_root), encoding="utf-8")
                files_written.append(str(conf_path.relative_to(ws_path)))
            else:
                instructions.append(f"Preserved existing {conf_path.name}")

            if not conv_path.exists():
                conv_path.write_text(_aider_conventions(aevoraseo_root), encoding="utf-8")
                files_written.append(str(conv_path.relative_to(ws_path)))
            else:
                instructions.append(f"Preserved existing {conv_path.name}")
        else:
            files_written.extend([".aider.conf.yml", ".aider.conventions.md"])

        instructions.append("Run aider with: aider --read SKILL.md")

    elif platform_id == PlatformId.COPILOT:
        github_dir = ws_path / ".github"
        target = github_dir / "copilot-instructions.md"

        if not dry_run:
            github_dir.mkdir(parents=True, exist_ok=True)
            if not target.exists():
                target.write_text(_copilot_instructions(aevoraseo_root), encoding="utf-8")
                files_written.append(str(target.relative_to(ws_path)))
            else:
                instructions.append(f"Preserved existing {target.name}")
        else:
            files_written.append(".github/copilot-instructions.md")

        instructions.append("Copilot will automatically read instructions in .github/copilot-instructions.md")

    elif platform_id == PlatformId.GEMINI_CLI:
        target = ws_path / "GEMINI.md"

        if not dry_run:
            if not target.exists():
                target.write_text(_gemini_instructions(aevoraseo_root), encoding="utf-8")
                files_written.append(str(target.relative_to(ws_path)))
            else:
                instructions.append(f"Preserved existing {target.name}")
        else:
            files_written.append("GEMINI.md")

        instructions.append("Gemini CLI will read instructions from GEMINI.md in workspace root")

    elif spec.tier == PlatformTier.FIRST_PARTY_SKILL:
        instructions.append(f"To install native skill for {spec.name}:")
        instructions.append(f"  {spec.install_command}")
        instructions.append(f"Skill location: {spec.skill_file_location}")
        instructions.append(f"Invocation: {spec.invocation}")

    else:
        # CLI integration / generic adapter
        instructions.append(f"To configure {spec.name}:")
        instructions.append(f"  Install: {spec.install_command}")
        instructions.append(f"  Skill location: {spec.skill_file_location}")
        instructions.append(f"  Invocation: {spec.invocation}")
        instructions.append(f"  Smoke test: {spec.smoke_test}")

    return AdapterResult(
        platform=platform_id,
        files_written=files_written,
        instructions="\n".join(instructions),
        dry_run=dry_run,
    )
